# Model Configuration
embedding:
  model_name: "sentence-transformers/all-mpnet-base-v2"
  device: "cuda"  # or "cpu" if no GPU available
  batch_size: 32
  normalize_embeddings: true

generation:
  model_name: "gpt-3.5-turbo"  # or any other LLM of your choice
  temperature: 0.7
  max_tokens: 500
  top_p: 0.9
  frequency_penalty: 0.0
  presence_penalty: 0.0

retrieval:
  top_k: 5  # Number of chunks to retrieve
  score_threshold: 0.7  # Minimum similarity score to consider
